### ISSUE TITLE
Each time I compile any example I have an error:   'AudioPrint' has not been declared

### ISSUE THREAD

**Issue by SurvivalHacking** [pschatzmann/SIDPlayer#13]
After a little check, i found that seem there are a double declaration in SIDPlayer.H

// SIDPlayer(AudioSource &source, AudioPrint &output, SizeSource &sizeSource) {
//    static CodecNOP nop;
//    p_size_source = &sizeSource;
//    player.setAudioSource(source);
//    player.setOutput(output);
//    p_info = &output;
//    p_out = &output;
//  }
  
  SIDPlayer(AudioSource &source, AudioStream &output, SizeSource &sizeSource) {
   static CodecNOP nop;
    p_size_source = &sizeSource;
    player.setAudioSource(source);
    player.setOutput(output);
    p_info = &output;
    p_out = &output;
  }
  
If I comment the first declaration that use AudioPrint, I can compile all without error, but there are not any audio output on AI Thinker Audio Kit C2.2 , but I think comment this part is not the right solution. There are some other missing ?

**Comment by SurvivalHacking** [comment]
Using AudioKit and commet the AudioPrint section it works

**Comment by pschatzmann** [comment]
I committed some corrections to support the actual version of the AudioTools
