### ISSUE TITLE
SID files do not end

### ISSUE THREAD

**Issue by pschatzmann** [pschatzmann/SIDPlayer#6]
### Discussed in https://github.com/pschatzmann/SIDPlayer/discussions/2

<div type='discussions-op-text'>

<sup>Originally posted by **pschatzmann** March  2, 2023</sup>
I noticed that at least the first SID file is playing forever. 
Is there a way to notice that we are at the end ?</div>

**Comment by beachviking** [comment]
I think the sid files are free to loop forever, if that is how they are set up with the 6510 instructions.

However, I see a 'finished' variable in the libcsid.cpp code at line 157 which we can take a closer look at to see if this can be used for anything useful in this respect.

**Comment by pschatzmann** [comment]
I just double checked: this variable is set to true thuout the song, so it is not really usefull.
So I think I just stick to my timeout to end it automatically...

**Comment by pschatzmann** [comment]
If you set the log level to debug you should see in detail what is called
